#include "distributed.hpp"
#include "taxonomy/partition.hpp"
#include "db/grd/grd_merge.hpp"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <spdlog/spdlog.h>
#include <string>
#include <vector>

namespace derep {

namespace fs = std::filesystem;

// ── scatter ──────────────────────────────────────────────────────────────────

int run_scatter(const Config& cfg) {
    fs::create_directories(cfg.scatter_dir);
    auto abs_scatter = fs::absolute(cfg.scatter_dir);

    // 1. Partition the input TSV
    taxonomy::PartitionConfig pcfg;
    pcfg.input_tsv  = cfg.tax_file;
    pcfg.output_dir = cfg.scatter_dir;
    pcfg.n_parts    = cfg.n_partitions;
    pcfg.rank       = cfg.partition_rank;
    size_t total = taxonomy::partition_tsv(pcfg);

    // 2. Generate worker script (run.sh)
    //    Each line is a self-contained geodesic derep command for one partition.
    //    Users can run these however they like: ssh, sbatch, xargs, GNU parallel.
    auto script_path = cfg.scatter_dir / "run.sh";
    {
        std::ofstream f(script_path);
        f << "#!/usr/bin/env bash\n"
          << "# Generated by: geodesic scatter\n"
          << "# " << cfg.n_partitions << " partitions, " << total << " genomes\n"
          << "#\n"
          << "# Run all partitions (example usage):\n"
          << "#   bash run.sh                         # sequential on this node\n"
          << "#   parallel -j4 < run.sh               # 4 at a time locally\n"
          << "#   while read cmd; do ssh node$i \"$cmd\" & ((i++)); done < run.sh\n"
          << "#\n"
          << "# Or submit to SLURM:\n"
          << "#   sbatch --array=0-" << (cfg.n_partitions - 1)
          << " --wrap 'sed -n \"$((SLURM_ARRAY_TASK_ID+1))p\" " << script_path.string()
          << " | bash'\n"
          << "#\n";

        // Build the base command (mirrors the derep options from the scatter invocation)
        std::string base_cmd;
        // Find geodesic binary — use argv[0] if available, else assume it's in PATH
        base_cmd = "geodesic derep";

        // Use explicit --tmp-dir only if the user set one; otherwise workers use
        // the scatter dir (their CWD) so temp files never land in /tmp by accident.
        fs::path worker_tmp = (cfg.tmp_dir != fs::path{"."})
                              ? fs::absolute(cfg.tmp_dir)
                              : abs_scatter;

        for (int i = 0; i < cfg.n_partitions; ++i) {
            auto part_tsv = abs_scatter / ("part_" + std::to_string(i) + ".tsv");
            auto grd_file = abs_scatter / ("shard_" + std::to_string(i) + ".grd");

            f << "cd " << abs_scatter.string() << " && " << base_cmd
              << " -t " << part_tsv.string()
              << " -p shard_" << i
              << " --threads " << cfg.threads;

            if (cfg.pack_dir.has_value())
                f << " --pack " << fs::absolute(*cfg.pack_dir).string();

            f << " --grd-output " << grd_file.string()
              << " --tmp-dir " << worker_tmp.string()
              << "\n";
        }
    }

    // Make executable
    fs::permissions(script_path,
                    fs::perms::owner_exec | fs::perms::group_exec | fs::perms::others_exec,
                    fs::perm_options::add);

    // 3. Write manifest (machine-readable JSON-lines)
    auto manifest_path = cfg.scatter_dir / "manifest.tsv";
    {
        std::ofstream f(manifest_path);
        f << "partition\ttsv\tgrd\tprefix\n";
        for (int i = 0; i < cfg.n_partitions; ++i) {
            f << i
              << "\t" << (cfg.scatter_dir / ("part_" + std::to_string(i) + ".tsv")).string()
              << "\t" << (cfg.scatter_dir / ("shard_" + std::to_string(i) + ".grd")).string()
              << "\tshard_" << i
              << "\n";
        }
    }

    spdlog::info("scatter: {} partitions written to {}", cfg.n_partitions,
                 cfg.scatter_dir.string());
    spdlog::info("scatter: run workers with: bash {}", script_path.string());
    spdlog::info("scatter: then merge with: geodesic gather -d {} -o results.grd",
                 cfg.scatter_dir.string());

    return 0;
}

// ── gather ───────────────────────────────────────────────────────────────────

int run_gather(const Config& cfg) {
    // 1. Find all GRD shards
    std::vector<fs::path> grd_shards;
    for (auto& entry : fs::directory_iterator(cfg.gather_dir)) {
        if (entry.path().extension() == ".grd" && entry.file_size() > 0)
            grd_shards.push_back(entry.path());
    }
    std::sort(grd_shards.begin(), grd_shards.end());

    if (grd_shards.empty()) {
        spdlog::error("gather: no .grd files found in {}", cfg.gather_dir.string());
        return 1;
    }

    spdlog::info("gather: found {} GRD shards", grd_shards.size());

    // 2. Merge GRD files
    auto stats = grd::merge_grd(grd_shards, cfg.gather_output);

    // 3. Merge TSV result files
    //    Look for shard_*/shard_*_derep_genomes.tsv, _results.tsv, etc.
    auto merge_tsv = [&](const std::string& suffix) {
        auto output_path = cfg.gather_output.parent_path() / (cfg.prefix + suffix);
        std::ofstream out(output_path);
        bool header_written = false;

        for (auto& entry : fs::recursive_directory_iterator(cfg.gather_dir)) {
            if (!entry.is_regular_file()) continue;
            if (entry.path().filename() == output_path.filename()) continue;
            auto fname = entry.path().filename().string();
            if (fname.find(suffix) == std::string::npos) continue;
            if (entry.path().extension() != ".tsv") continue;

            std::ifstream in(entry.path());
            std::string line;
            bool first_line = true;
            while (std::getline(in, line)) {
                if (first_line) {
                    first_line = false;
                    if (!header_written) {
                        out << line << "\n";
                        header_written = true;
                    }
                    continue;  // skip header in subsequent files
                }
                if (!line.empty())
                    out << line << "\n";
            }
        }

        if (header_written)
            spdlog::info("gather: merged {} → {}", suffix, output_path.string());
    };

    merge_tsv("_derep_genomes.tsv");
    merge_tsv("_results.tsv");
    merge_tsv("_stats.tsv");
    merge_tsv("_diversity_stats.tsv");
    merge_tsv("_outliers.tsv");

    spdlog::info("gather: done — {} taxa, {} genomes → {}",
                 stats.n_taxa, stats.n_genomes, cfg.gather_output.string());

    return 0;
}

} // namespace derep
